#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config{/log/rutorrent,/rutorrent/settings/users} \
	/config/rutorrent/profiles{/settings,/torrents,/users,/tmp} \
	/run/php

cd /defaults/rutorrent-conf || exit
shopt -s globstar nullglob
for i in *
do
	[[ ! -e "/config/rutorrent/settings/${i}" ]] && cp -v "${i}" "/config/rutorrent/settings/${i}"
done

[[ ! -e rtorrent_config/.rtorrent.rc ]] && \
	cp /defaults/rtorrent.rc /rtorrent_config/.rtorrent.rc
cp -pr /config/rutorrent/settings/* /app/rutorrent/conf/

# copy over any theme files to themes folder
[[ -e /config/themes ]] && \
	cp -R /config/themes/ /app/rutorrent/plugins/theme/

# copy over any plugins to the plugins folder
[[ -e /config/plugins ]] && \
	cp -R /config/plugins/ /app/rutorrent/

# delete lock file if exists
[[ -e /rtorrent_config/.session/rtorrent.lock ]] && \
	rm /rtorrent_config/.session/rtorrent.lock

# permissions

chown -R abc:abc \
	/config \
	/run \
	/app/rutorrent

chmod -R 755 /config/rutorrent/profiles
